<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Job; // <-- 1. IMPORT MODEL KITA
use Illuminate\Support\Facades\DB;

class JobSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 2. Kosongkan tabelnya dulu
        DB::table('jobs')->truncate();

        // 3. Siapkan data
        $jobs = [
            // --- DATA MAGANG (16 item) ---
            [
                'title' => 'UI/UX Designer',
                'description' => 'Merancang antarmuka pengguna yang intuitif dan pengalaman pengguna...',
                'category' => 'Design',
                'type' => 'Magang',
                'level' => 'Beginner',
                'duration' => '3-6 bulan',
                'requirements' => json_encode(['Mahasiswa Desain/Informatika', 'Menguasai Figma/Adobe XD']),
                'benefits' => json_encode(['Sertifikat', 'Uang saku', 'Mentoring']),
                'responsibilities' => null, 'posted_at' => null, 'location' => null, 'salary' => null, 'experience' => null,
            ],
            [
                'title' => 'Frontend Developer',
                'description' => 'Mengembangkan tampilan website dan aplikasi menggunakan teknologi...',
                'category' => 'Programming',
                'type' => 'Magang',
                'level' => 'Intermediate',
                'duration' => '3-6 bulan',
                'requirements' => json_encode(['Mahasiswa Informatika/Teknik', 'Menguasai HTML, CSS, JavaScript', 'Familiar dengan React.js']),
                'benefits' => json_encode(['Sertifikat', 'Uang saku', 'Project portfolio']),
                'responsibilities' => null, 'posted_at' => null, 'location' => null, 'salary' => null, 'experience' => null,
            ],
            [
                'title' => 'Backend Developer',
                'description' => 'Membangun sistem backend, API, dan database untuk mendukung...',
                'category' => 'Programming',
                'type' => 'Magang',
                'level' => 'Intermediate',
                'duration' => '3-6 bulan',
                'requirements' => json_encode(['Mahasiswa Informatika/Teknik', 'Menguasai PHP/Python/Node.js']),
                'benefits' => json_encode(['Sertifikat', 'Uang saku', 'Technical mentoring']),
                'responsibilities' => null, 'posted_at' => null, 'location' => null, 'salary' => null, 'experience' => null,
            ],
            [
                'title' => 'Human Resource',
                'description' => 'Mengelola rekrutmen, administrasi karyawan, dan pengembangan...',
                'category' => 'Management',
                'type' => 'Magang',
                'level' => 'Beginner',
                'duration' => '3-4 bulan',
                'requirements' => json_encode(['Mahasiswa Psikologi/Manajemen', 'Komunikasi baik']),
                'benefits' => json_encode(['Sertifikat', 'Networking', 'HR experience']),
                'responsibilities' => null, 'posted_at' => null, 'location' => null, 'salary' => null, 'experience' => null,
            ],
            [
                'title' => 'Administrasi',
                'description' => 'Mengelola dokumen, data entry, dan mendukung operasional kantor...',
                'category' => 'Management',
                'type' => 'Magang',
                'level' => 'Beginner',
                'duration' => '3-4 bulan',
                'requirements' => json_encode(['Mahasiswa semua jurusan', 'Teliti & rapi', 'MS Office']),
                'benefits' => json_encode(['Sertifikat', 'Uang saku', 'Office skills']),
                'responsibilities' => null, 'posted_at' => null, 'location' => null, 'salary' => null, 'experience' => null,
            ],
            [
                'title' => 'Social Media Specialist',
                'description' => 'Mengelola konten media sosial, engagement, dan berbagai platform...',
                'category' => 'Marketing',
                'type' => 'Magang',
                'level' => 'Beginner',
                'duration' => '3-6 bulan',
                'requirements' => json_encode(['Mahasiswa Komunikasi/Marketing', 'Kreatif']),
                'benefits' => json_encode(['Sertifikat', 'Portfolio', 'Digital marketing skills']),
                'responsibilities' => null, 'posted_at' => null, 'location' => null, 'salary' => null, 'experience' => null,
            ],
            [
                'title' => 'Photographer/Videographer',
                'description' => 'Mengambil foto dan video untuk kebutuhan konten, dokumentasi...',
                'category' => 'Creative',
                'type' => 'Magang',
                'level' => 'Intermediate',
                'duration' => '3-6 bulan',
                'requirements' => json_encode(['Portfolio foto/video', 'Kamera DSLR/Mirrorless']),
                'benefits' => json_encode(['Sertifikat', 'Equipment access', 'Creative portfolio']),
                'responsibilities' => null, 'posted_at' => null, 'location' => null, 'salary' => null, 'experience' => null,
            ],
            [
                'title' => 'Content Writer',
                'description' => 'Menulis artikel, blog, caption, dan berbagai konten kreatif...',
                'category' => 'Creative',
                'type' => 'Magang',
                'level' => 'Beginner',
                'duration' => '3-6 bulan',
                'requirements' => json_encode(['Mahasiswa Sastra/Komunikasi', 'Writing skills']),
                'benefits' => json_encode(['Sertifikat', 'Writing portfolio', 'SEO training']),
                'responsibilities' => null, 'posted_at' => null, 'location' => null, 'salary' => null, 'experience' => null,
            ],
            [
                'title' => 'Graphic Designer',
                'description' => 'Membuat desain grafis untuk keperluan branding, promosi...',
                'category' => 'Design',
                'type' => 'Magang',
                'level' => 'Intermediate',
                'duration' => '3-6 bulan',
                'requirements' => json_encode(['Portfolio desain', 'Adobe Creative Suite']),
                'benefits' => json_encode(['Sertifikat', 'Design portfolio', 'Creative mentoring']),
                'responsibilities' => null, 'posted_at' => null, 'location' => null, 'salary' => null, 'experience' => null,
            ],
            [
                'title' => 'Digital Marketing',
                'description' => 'Mengelola kampanye digital, SEO, SEM, dan analisis performa...',
                'category' => 'Marketing',
                'type' => 'Magang',
                'level' => 'Intermediate',
                'duration' => '3-6 bulan',
                'requirements' => json_encode(['Mahasiswa Marketing/Komunikasi', 'Google Ads/Analytics']),
                'benefits' => json_encode(['Sertifikat', 'Google certification', 'Marketing experience']),
                'responsibilities' => null, 'posted_at' => null, 'location' => null, 'salary' => null, 'experience' => null,
            ],
            [
                'title' => 'Marcomm/Public Relations',
                'description' => 'Mengelola komunikasi eksternal, press release, dan membangun...',
                'category' => 'Communication',
                'type' => 'Magang',
                'level' => 'Intermediate',
                'duration' => '3-6 bulan',
                'requirements' => json_encode(['Mahasiswa Komunikasi/PR', 'Writing skills']),
                'benefits' => json_encode(['Sertifikat', 'Media relations', 'Communication skills']),
                'responsibilities' => null, 'posted_at' => null, 'location' => null, 'salary' => null, 'experience' => null,
            ],
            [
                'title' => 'Host/Presenter',
                'description' => 'Menjadi pembawa acara untuk event, webinar, dan konten video...',
                'category' => 'Communication',
                'type' => 'Magang',
                'level' => 'Beginner',
                'duration' => '3-6 bulan',
                'requirements' => json_encode(['Public speaking', 'Confident']),
                'benefits' => json_encode(['Sertifikat', 'Speaking experience', 'Personal branding']),
                'responsibilities' => null, 'posted_at' => null, 'location' => null, 'salary' => null, 'experience' => null,
            ],
            [
                'title' => 'TikTok Creator',
                'description' => 'Membuat konten kreatif dan viral untuk platform TikTok...',
                'category' => 'Creative',
                'type' => 'Magang',
                'level' => 'Beginner',
                'duration' => '3-6 bulan',
                'requirements' => json_encode(['Kreatif', 'Familiar dengan TikTok']),
                'benefits' => json_encode(['Sertifikat', 'Content portfolio', 'Social media growth']),
                'responsibilities' => null, 'posted_at' => null, 'location' => null, 'salary' => null, 'experience' => null,
            ],
            [
                'title' => 'Content Planner',
                'description' => 'Merencanakan strategi konten, editorial calendar, dan koordinasi...',
                'category' => 'Marketing',
                'type' => 'Magang',
                'level' => 'Intermediate',
                'duration' => '3-6 bulan',
                'requirements' => json_encode(['Strategic thinking', 'Project management']),
                'benefits' => json_encode(['Sertifikat', 'Planning skills', 'Strategy experience']),
                'responsibilities' => null, 'posted_at' => null, 'location' => null, 'salary' => null, 'experience' => null,
            ],
            [
                'title' => 'Project Manager',
                'description' => 'Mengelola proyek dari perencanaan hingga eksekusi, koordinasi tim...',
                'category' => 'Management',
                'type' => 'Magang',
                'level' => 'Advanced',
                'duration' => '4-6 bulan',
                'requirements' => json_encode(['Leadership skills', 'Project management tools']),
                'benefits' => json_encode(['Sertifikat', 'PM certification', 'Leadership experience']),
                'responsibilities' => null, 'posted_at' => null, 'location' => null, 'salary' => null, 'experience' => null,
            ],
            [
                'title' => 'Animator',
                'description' => 'Membuat animasi 2D/3D untuk keperluan promosi, explainer video...',
                'category' => 'Creative',
                'type' => 'Magang',
                'level' => 'Advanced',
                'duration' => '3-6 bulan',
                'requirements' => json_encode(['Portfolio animasi', 'After Effects/Blender']),
                'benefits' => json_encode(['Sertifikat', 'Animation portfolio', 'Technical skills']),
                'responsibilities' => null, 'posted_at' => null, 'location' => null, 'salary' => null, 'experience' => null,
            ],

            // --- DATA LOWONGAN KERJA (6 item) ---
            [
                'title' => 'Senior UI/UX Designer',
                'description' => 'Memimpin tim design dan mengembangkan design system untuk produk digital perusahaan.',
                'category' => 'Design',
                'type' => 'Full-time',
                'level' => null,
                'duration' => null,
                'posted_at' => '2 hari lalu',
                'location' => 'Yogyakarta',
                'salary' => 'Rp 8-12 juta',
                'experience' => '3+ tahun',
                'requirements' => json_encode(['S1 Desain/terkait', '3+ tahun experience', 'Leadership skills', 'Portfolio strong', 'Figma/Adobe XD expert']),
                'benefits' => json_encode(['BPJS Kesehatan', 'Bonus tahunan', 'Flexible working', 'Training budget']),
                'responsibilities' => json_encode(['Lead design team', 'Create design system', 'User research', 'Prototype development']),
            ],
            [
                'title' => 'Full Stack Developer',
                'description' => 'Mengembangkan aplikasi web end-to-end dengan teknologi modern dan best practices.',
                'category' => 'Engineering',
                'type' => 'Full-time',
                'level' => null,
                'duration' => null,
                'posted_at' => '1 minggu lalu',
                'location' => 'Yogyakarta',
                'salary' => 'Rp 10-15 juta',
                'experience' => '2+ tahun',
                'requirements' => json_encode(['S1 Informatika', 'React/Vue + Node.js', 'Database design', 'API development', 'Git workflow']),
                'benefits' => json_encode(['BPJS Kesehatan', 'Laptop provided', 'Remote work option', 'Career development']),
                'responsibilities' => json_encode(['Full-stack development', 'Code review', 'System architecture', 'Performance optimization']),
            ],
            [
                'title' => 'Digital Marketing Manager',
                'description' => 'Mengelola strategi digital dan memimpin tim marketing digital untuk mencapai target bisnis.',
                'category' => 'Marketing',
                'type' => 'Full-time',
                'level' => null,
                'duration' => null,
                'posted_at' => '3 hari lalu',
                'location' => 'Yogyakarta',
                'salary' => 'Rp 7-10 juta',
                'experience' => '2+ tahun',
                'requirements' => json_encode(['S1 Marketing/Komunikasi', 'Google Ads certified', 'Team management', 'Data analysis', 'Social media expertise']),
                'benefits' => json_encode(['BPJS Kesehatan', 'Marketing budget', 'Conference attendance', 'Performance bonus']),
                'responsibilities' => json_encode(['Marketing strategy', 'Team leadership', 'Campaign management', 'ROI analysis']),
            ],
            [
                'title' => 'Content Creator',
                'description' => 'Membuat konten kreatif untuk berbagai platform digital dan social media dengan konsistensi brand.',
                'category' => 'Creative',
                'type' => 'Contract',
                'level' => null,
                'duration' => null,
                'posted_at' => '5 hari lalu',
                'location' => 'Yogyakarta',
                'salary' => 'Rp 5-8 juta',
                'experience' => '1+ tahun',
                'requirements' => json_encode(['Portfolio konten', 'Video editing', 'Photography', 'Social media savvy', 'Creative thinking']),
                'benefits' => json_encode(['Equipment provided', 'Creative freedom', 'Flexible schedule', 'Portfolio building']),
                'responsibilities' => json_encode(['Content creation', 'Social media management', 'Brand storytelling', 'Trend analysis']),
            ],
            [
                'title' => 'Project Manager',
                'description' => 'Mengelola proyek digital dari inisiasi hingga delivery dengan metodologi agile dan waterfall.',
                'category' => 'Management',
                'type' => 'Full-time',
                'level' => null,
                'duration' => null,
                'posted_at' => '1 hari lalu',
                'location' => 'Yogyakarta',
                'salary' => 'Rp 9-13 juta',
                'experience' => '3+ tahun',
                'requirements' => json_encode(['S1 semua jurusan', 'PMP/Scrum certified', 'Project management tools', 'Leadership', 'Communication skills']),
                'benefits' => json_encode(['BPJS Kesehatan', 'Certification support', 'Leadership training', 'Annual bonus']),
                'responsibilities' => json_encode(['Project planning', 'Team coordination', 'Risk management', 'Stakeholder communication']),
            ],
            [
                'title' => 'Data Analyst',
                'description' => 'Menganalisis data bisnis dan memberikan insights untuk mendukung pengambilan keputusan strategis.',
                'category' => 'Analytics',
                'type' => 'Full-time',
                'level' => null,
                'duration' => null,
                'posted_at' => '4 hari lalu',
                'location' => 'Yogyakarta',
                'salary' => 'Rp 6-9 juta',
                'experience' => '1+ tahun',
                'requirements' => json_encode(['S1 Statistik/Matematika', 'SQL, Python/R', 'Data visualization', 'Statistical analysis', 'Business acumen']),
                'benefits' => json_encode(['BPJS Kesehatan', 'Learning budget', 'Data tools access', 'Flexible hours']),
                'responsibilities' => json_encode(['Data analysis', 'Report creation', 'Dashboard development', 'Business insights']),
            ],
        ];

        // 4. Masukkan semua data ke database
        Job::insert($jobs);
    }
}